from django.core.management.base import BaseCommand
from core.models import Product


class Command(BaseCommand):
    help = 'Import 10 premium couture bridal products with multilingual support'

    def handle(self, *args, **options):
        products_data = [
            {
                'model': 105,
                'name_mk': 'Принцеза Модел 105',
                'name_tr': 'Prenses Model 105',
                'name_sq': 'Modeli i Princeshës 105',
                'summary_mk': 'Раскошна принцеза венчаница со долг вел',
                'summary_tr': 'Lüks prenses gelinliği uzun tülbentle',
                'summary_sq': 'Pasuri princeshë nuse me mbulesë të gjatë',
                'description_mk': 'Екскузивна принцеза венчаница со деликатни детали и волупутни слоеви. Совршена за невести што сакаат раскош и грациозност.',
                'description_tr': 'Eksklusif prenses gelinliği hassas detaylarla ve volüplü katmanlarla. Lüksü ve zarafeti seven gelinler için mükemmel.',
                'description_sq': 'Ekskluzive modeli i princeshës me detaje delikate dhe shtresa volupt. Përsosur për nuset që dëshirojnë pasuri dhe elegancë.',
                'category': 'princess',
            },
            {
                'model': 106,
                'name_mk': 'А-линија Модел 106',
                'name_tr': 'A Kesim Model 106',
                'name_sq': 'Modeli A-linjë 106',
                'summary_mk': 'Елегантна А-линија венчаница за секоја фигура',
                'summary_tr': 'Zarif A kesim gelinliği her gövdeye uygun',
                'summary_sq': 'Elegante A-linjë nuse e përshtatshme për çdo figurë',
                'description_mk': 'Класична А-линија што флатира секоја фигура. Изработена од премиум материјали со внимателен дизајн.',
                'description_tr': 'Her vücut tipine yakışan klasik A kesimi. Premium malzemelerden dikkatli tasarımla yapılmış.',
                'description_sq': 'Forma klasike A-linjes që nuk i bëhet ndonjë figure. Bërë me materiale premium me dizajn të kujdesshëm.',
                'category': 'a_line',
            },
            {
                'model': 107,
                'name_mk': 'Русалка Модел 107',
                'name_tr': 'Balık Model 107',
                'name_sq': 'Modeli i Sirenës 107',
                'summary_mk': 'Соблазнител русалка венчаница со дерзни криви',
                'summary_tr': 'Kusursuz balık gelinliği cesur eğrilerle',
                'summary_sq': 'Modeli i sirenës që tundot me kthesa të guximshme',
                'description_mk': 'Русалка венчаница која нагласува природни криви со софистицирана елеганција. За невести со јачина и стил.',
                'description_tr': 'Doğal eğrileri sofistike zarafetle vurgulayan balık gelinliği. Güc ve tarzı olan gelinler için.',
                'description_sq': 'Modeli i sirenës që thekson kthesat natyrore me elegancë të sofistikuar. Për nuset me fuqi dhe stil.',
                'category': 'mermaid',
            },
            {
                'model': 108,
                'name_mk': 'Минимал Модел 108',
                'name_tr': 'Minimal Model 108',
                'name_sq': 'Modeli Minimale 108',
                'summary_mk': 'Современна минимална венчаница со чистити линии',
                'summary_tr': 'Çağdaş minimal gelinliği temiz çizgilerle',
                'summary_sq': 'Modeli minimal kontemporare me linja të pastra',
                'description_mk': 'Минимална венчаница која го прославува едноставноста и современниот дизајн. Совршена за невести што го ценат едноставниот елеганс.',
                'description_tr': 'Basitliği ve çağdaş tasarımı kutlayan minimal gelinliği. Basit zarafeti seven gelinler için mükemmel.',
                'description_sq': 'Modeli minimal që nderojnë thjeshtësinë dhe dizajnin bashkëkohor. Për nuset që vlerësojnë elegancën e thjeshtë.',
                'category': 'minimal',
            },
            {
                'model': 109,
                'name_mk': 'Класик Модел 109',
                'name_tr': 'Klasik Model 109',
                'name_sq': 'Modeli Klasik 109',
                'summary_mk': 'Безвремска класична венчаница со вечна елеганција',
                'summary_tr': 'Sonsuz klasik gelinliği ebedi zarafetle',
                'summary_sq': 'Modeli klasik pa kohë me elegancë përjetshme',
                'description_mk': 'Класична венчаница која никогаш не станува модна. Изработена со совршена мастрија и најфини материјали.',
                'description_tr': 'Asla modası geçmeyen klasik gelinliği. Mükemmel ustalık ve en ince malzemelerle yapılmış.',
                'description_sq': 'Modeli klasik i cili nuk humbet asnjëherë trendin. I bërë me përpunim të përsosur dhe materiale më të imëta.',
                'category': 'classic',
            },
            {
                'model': 110,
                'name_mk': 'Принцеза со шипки Модел 110',
                'name_tr': 'Prenses Dantelli Model 110',
                'name_sq': 'Modeli Princa me Çipë 110',
                'summary_mk': 'Раскошна шипката принцеза со ручно постављена декорација',
                'summary_tr': 'Lüks dantel prenses manuel dekorasyon ile',
                'summary_sq': 'Pasuri çipë princeshë me dekorime të dorës',
                'description_mk': 'Премиум принцеза венчаница со детална шипка и ручно постављена секвенцијална декорација. За особени неверести.',
                'description_tr': 'Detaylı dantel ve manuel sıralı dekorasyon ile premium prenses gelinliği. Özel gelinler için.',
                'description_sq': 'Çipë me detaje premium dhe dekorime të sekuencës dore. Për nuset e veçanta.',
                'category': 'princess',
            },
            {
                'model': 111,
                'name_mk': 'А-линија Империја Модел 111',
                'name_tr': 'A Kesim Empire Model 111',
                'name_sq': 'A-linjë Perandorakë Modeli 111',
                'summary_mk': 'Класична А-линија со ѕивот под грудата',
                'summary_tr': 'Göğüs altında belirli A kesim klasik',
                'summary_sq': 'A-linjë klasike me dorezën nën gjoks',
                'description_mk': 'А-линија венчаница со империјален ѕивот која ги флатира сите типови на телото. Невајно да си бремена или не.',
                'description_tr': 'İmparatorluk belirtili A kesim gelinliği tüm vücut tiplerini güzelleştirir. Hamile olsun ya da olmasın.',
                'description_sq': 'A-linjë nuse me dorezë perandorake e cila zbukuron të gjitha tipat e trupit. Pavarësisht nëse jeni shtatzënë apo jo.',
                'category': 'a_line',
            },
            {
                'model': 112,
                'name_mk': 'Русалка Атлас Модел 112',
                'name_tr': 'Balık Saten Model 112',
                'name_sq': 'Modeli i Sirenës me Satin 112',
                'summary_mk': 'Сатинска русалка венчаница со дневни криви',
                'summary_tr': 'Saten balık gelinliği gün eğrileriyle',
                'summary_sq': 'Modeli i sirenës me satin dhe kthesat e ditës',
                'description_mk': 'Премиум сатинска русалка венчаница со мека и свилена финиција. Буквално граѓа за да се чувствувате божествено.',
                'description_tr': 'Premium saten balık gelinliği yumuşak ve ipek bitirişle. Tanrısal hissetmek için yapıldı.',
                'description_sq': 'Premium satin modeli i sirenës me përfundim të butë dhe të mëndafshit. I ndërtuar për të ndjerë divinare.',
                'category': 'mermaid',
            },
            {
                'model': 113,
                'name_mk': 'Модерен Минимал Модел 113',
                'name_tr': 'Modern Minimal Model 113',
                'name_sq': 'Modeli Modern Minimale 113',
                'summary_mk': 'Авангардно минимална венчаница за смелите неверести',
                'summary_tr': 'Cesur gelinler için avangard minimal gelinlik',
                'summary_sq': 'Modeli avangard minimal për nuset e guximshme',
                'description_mk': 'Смела минимална венчаница со неочекувани деталиња. За невести со уникатен вкус и артистички дух.',
                'description_tr': 'Beklenmedik detaylarla cesur minimal gelinliği. Benzersiz tasta ve sanatsal ruhu olan gelinler için.',
                'description_sq': 'Modeli minimal i guximshëm me detaje të papritur. Për nuset me shije unike dhe shpirt artistik.',
                'category': 'minimal',
            },
            {
                'model': 114,
                'name_mk': 'Класична Винтаж Модел 114',
                'name_tr': 'Klasik Vintage Model 114',
                'name_sq': 'Modeli Klasik Vintage 114',
                'summary_mk': 'Винтаж венчаница со ретро шарм и модерна шик',
                'summary_tr': 'Retro şarm ve modern şık ile vintage gelinlik',
                'summary_sq': 'Modeli vintage me charme retro dhe chik modern',
                'description_mk': 'Класична винтаж венчаница која ги спојува старите денови со современниот дизајн. За невести со ностална душа.',
                'description_tr': 'Eski günleri çağдаş tasarımla birleştiren klasik vintage gelinliği. Nostaljik ruhlu gelinler için.',
                'description_sq': 'Modeli klasik vintage i cili kombinon ditët e vjetra me dizajnin bashkëkohor. Për nuset me shpirt nostalgji.',
                'category': 'classic',
            },
            {
                'model': 115,
                'name_mk': 'Прозирна Шипка Модел 115',
                'name_tr': 'Şeffaf Dantel Model 115',
                'name_sq': 'Modeli i Çipës Transparente 115',
                'summary_mk': 'Елегантна венчаница со прозирни шипки детали',
                'summary_tr': 'Şeffaf dantel detaylarla zarif gelinliği',
                'summary_sq': 'Elegante nuse me detaje çipe transparente',
                'description_mk': 'Премиум венчаница со воздушни прозирни шипки што создава роман и мистика. За невести што го ценат утонченост.',
                'description_tr': 'Hava gibi şeffaf dantel detaylarla romantik ve mistik bir görünüm yaratan premium gelinliği. Incelik seven gelinler için.',
                'description_sq': 'Modeli premium me detaje çipe transparente të ajërorur që krijon pamje romantike dhe misterioze. Për nuset që vlerësojnë hollësinë.',
                'category': 'princess',
            },
            {
                'model': 116,
                'name_mk': 'А-линија Корсет Модел 116',
                'name_tr': 'A Kesim Korse Model 116',
                'name_sq': 'A-linjë Korset Modeli 116',
                'summary_mk': 'А-линија венчаница со чврст корсет торс',
                'summary_tr': 'Sıkı korset yapılı A kesim gelinliği',
                'summary_sq': 'A-linjë nuse me korset të ngurtë të trupit',
                'description_mk': 'Класична А-линија со елегантен корсет што го обликува торсот совршено. За невести што сакаат дефиниран силует.',
                'description_tr': 'Vücut şeklini mükemmel şekilde belirleyen zarif korset yapılı klasik A kesimi. Tanımlı bir siluet isteyen gelinler için.',
                'description_sq': 'Forma klasike A-linjes me korset elegant që përcakton trupin përsosur. Për nuset që dëshirojnë një silhuetë të përcaktuar.',
                'category': 'a_line',
            },
            {
                'model': 117,
                'name_mk': 'Русалка Перли Модел 117',
                'name_tr': 'Balık İnci Model 117',
                'name_sq': 'Modeli i Sirenës me Perla 117',
                'summary_mk': 'Раскошна русалка со перли и крајали украс',
                'summary_tr': 'İnci ve boncuk detaylarla lüks balık gelinliği',
                'summary_sq': 'Modeli i sirenës pasuri me dekorime perle dhe margjetat',
                'description_mk': 'Раскошна русалка венчаница со рачно постављени перли и крајали што создаст блещав изглед. За невести со жичка.',
                'description_tr': 'Manuel olarak yerleştirilen inci ve boncuklar ile parlak bir görünüm yaratan lüks balık gelinliği. Cesur gelinler için.',
                'description_sq': 'Modeli i sirenës pasuri me perla dhe margjetat e vendosura dorazi që krijon një shfaqje shkëlqyese. Për nuset me shpirt.',
                'category': 'mermaid',
            },
            {
                'model': 118,
                'name_mk': 'Минимал Џибон Модел 118',
                'name_tr': 'Minimal İpek Model 118',
                'name_sq': 'Modeli Minimale i Mëndafshit 118',
                'summary_mk': 'Едноставна минимална венчаница од чиста ипек',
                'summary_tr': 'Saf ipekten yapılı basit minimal gelinliği',
                'summary_sq': 'Modeli minimal i thjeshtë i bërë nga mëndafsh i pastër',
                'description_mk': 'Чиста ипека во едноставна минимална форма - совршено за невести со рафинирана апетита.',
                'description_tr': 'Saf ipekten yapılı basit minimal form - rafine zevke sahip gelinler için mükemmel.',
                'description_sq': 'Mëndafshi i pastër në formë minimale të thjeshtë - përsosur për nuset me shije të rafinuar.',
                'category': 'minimal',
            },
            {
                'model': 119,
                'name_mk': 'Класик Болеро Модел 119',
                'name_tr': 'Klasik Bolero Model 119',
                'name_sq': 'Modeli Klasik Bolero 119',
                'summary_mk': 'Венчаница со кус болеро јакна за повеќе варијабилност',
                'summary_tr': 'Kısa bolero ceket ile daha esnek gelinliği',
                'summary_sq': 'Nuse me xhaketë të shkurtër bolero për më shumë fleksibilitet',
                'description_mk': 'Класична венчаница што се комбинира со кус болеро јакна за денот и вечерта. За невести што сакаат флексибилност.',
                'description_tr': 'Gün ve akşam için kısa bolero ceketi ile kombinatif klasik gelinliği. Esneklik isteyen gelinler için.',
                'description_sq': 'Modeli klasik që kombinohet me një xhaketë të shkurtër bolero për ditën dhe mbrëmjen. Për nuset që dëshirojnë fleksibilitet.',
                'category': 'classic',
            },
            {
                'model': 120,
                'name_mk': 'Принцеза Плете Модел 120',
                'name_tr': 'Prenses Örgü Model 120',
                'name_sq': 'Modeli i Princeshës me Thurje 120',
                'summary_mk': 'Роман принцеза венчаница со плетена украс',
                'summary_tr': 'Örgü detaylarla romantik prenses gelinliği',
                'summary_sq': 'Modeli romantik i princeshës me dekorime thurjeje',
                'description_mk': 'Раскошна принцеза венчаница со детална плетена украс што ја создаст магичната атмосфера на сказки.',
                'description_tr': 'Masallarda görülen büyüleyici bir atmosfer yaratan detaylı örgü süslemeli lüks prenses gelinliği.',
                'description_sq': 'Modeli i pasuri i princeshës me dekorime detajore thurjeje që krijon një atmosferë magjike të përrallave.',
                'category': 'princess',
            },
            {
                'model': 121,
                'name_mk': 'А-линија Расел Модел 121',
                'name_tr': 'A Kesim Krepşıker Model 121',
                'name_sq': 'A-linjë Krep Modeli 121',
                'summary_mk': 'А-линија венчаница од текстуриран расел материјал',
                'summary_tr': 'Dokulu krepşuker malzemeden A kesim gelinliği',
                'summary_sq': 'A-linjë nuse e bërë nga materiale krep me teksturë',
                'description_mk': 'Елегантна А-линија венчаница од висококачествен расел што ја обезбедува удобност и стил во исто време.',
                'description_tr': 'Rahat ve stil aynı anda sağlayan yüksek kaliteli krepşuker malzemeden yapılmış zarif A kesim gelinliği.',
                'description_sq': 'Elegante A-linjë nuse e bërë nga materiale krep e lartë cilësi që përfshin rehati dhe stil në të njëjtën kohë.',
                'category': 'a_line',
            },
            {
                'model': 122,
                'name_mk': 'Русалка Гама Модел 122',
                'name_tr': 'Balık Ombre Model 122',
                'name_sq': 'Modeli i Sirenës Ombre 122',
                'summary_mk': 'Русалка венчаница со ombre боја градиент',
                'summary_tr': 'Ombre renk gradyanı ile balık gelinliği',
                'summary_sq': 'Modeli i sirenës me gradient ngjyrash ombre',
                'description_mk': 'Модерна русалка венчаница со красиво ombre боја што премина од темна во светла. За невести со модерен вкус.',
                'description_tr': 'Koyu ten açık renge güzel şekilde geçen ombre renk gradyanı ile modern balık gelinliği. Modern zevke sahip gelinler için.',
                'description_sq': 'Modeli modern i sirenës me gradient ngjyrash ombre të bukur që kalojnë nga ngjyra e ndritshme. Për nuset me shije moderne.',
                'category': 'mermaid',
            },
            {
                'model': 123,
                'name_mk': 'Минимал Скулптор Модел 123',
                'name_tr': 'Minimal Heykeltıraş Model 123',
                'name_sq': 'Modeli Minimal Skulpturor 123',
                'summary_mk': 'Авангардна минимална венчаница со геометриски облици',
                'summary_tr': 'Geometrik şekillerle avangard minimal gelinliği',
                'summary_sq': 'Modeli minimal avangard me forma gjeometrike',
                'description_mk': 'Смела минимална венчаница со геометриски облици што создаст уникатна визуелна структура. За невести со артистички вкус.',
                'description_tr': 'Benzersiz görsel yapı yaratan geometrik şekillerle cesur minimal gelinliği. Sanatsal zevke sahip gelinler için.',
                'description_sq': 'Modeli minimal i guximshëm me forma gjeometrike që krijon një strukturë vizuale unike. Për nuset me shije artistike.',
                'category': 'minimal',
            },
            {
                'model': 124,
                'name_mk': 'Класик Апликеј Модел 124',
                'name_tr': 'Klasik Aplikasyon Model 124',
                'name_sq': 'Modeli Klasik me Aplikacion 124',
                'summary_mk': 'Венчаница со апликеј украс на стратешни места',
                'summary_tr': 'Stratejik yerlerde aplikasyon süsleme ile gelinliği',
                'summary_sq': 'Nuse me dekorime aplikacioni në vende strategjike',
                'description_mk': 'Елегантна венчаница со деликатни апликеј украси на стратешни места што ја нагласува фигурата. За невести со рафинирана апетита.',
                'description_tr': 'Vücudu vurgulayan stratejik yerlerde delicate aplikasyon süslemeli zarif gelinliği. Rafine zevke sahip gelinler için.',
                'description_sq': 'Elegante nuse me dekorime aplikacioni delikate në vende strategjike që thekson figurën. Për nuset me shije të rafinuar.',
                'category': 'classic',
            },
            {
                'model': 125,
                'name_mk': 'Принцеза Фиоранто Модел 125',
                'name_tr': 'Prenses Fırfır Model 125',
                'name_sq': 'Modeli i Princeshës me Valëzime 125',
                'summary_mk': 'Раскошна принцеза венчаница со слоеви фиоранто',
                'summary_tr': 'Katmanlar fırfırlı lüks prenses gelinliği',
                'summary_sq': 'Modeli i pasuri i princeshës me shtresa valëzuese',
                'description_mk': 'Раскошна принцеза венчаница со многу слоеви фиоранто што создаст волумен и движење. За невести што сакаат драма.',
                'description_tr': 'Hacim ve hareket yaratan çoklu katmanlar fırfırlı lüks prenses gelinliği. Drama isteyen gelinler için.',
                'description_sq': 'Modeli i pasuri i princeshës me shumë shtresa valëzuese që krijon vëllim dhe lëvizje. Për nuset që dëshirojnë dramë.',
                'category': 'princess',
            },
            {
                'model': 126,
                'name_mk': 'А-линија Чипка Модел 126',
                'name_tr': 'A Kesim Dantel Model 126',
                'name_sq': 'A-linjë me Çipë Modeli 126',
                'summary_mk': 'А-линија венчаница со целосна шипка покривка',
                'summary_tr': 'Tam dantel kaplamalı A kesim gelinliği',
                'summary_sq': 'A-linjë nuse me mbulese të plotë çipe',
                'description_mk': 'Елегантна А-линија венчаница целосно покриена со фина шипка. Совршена комбинација од класика и романтика.',
                'description_tr': 'İnce dantel ile tamamen kaplı zarif A kesim gelinliği. Klasik ve romantizmin mükemmel kombinasyonu.',
                'description_sq': 'Elegante A-linjë nuse plotësisht e mbuluar me çipë të imët. Kombinimi përsosur i klasikës dhe romantizmit.',
                'category': 'a_line',
            },
            {
                'model': 127,
                'name_mk': 'Русалка Сатин Модел 127',
                'name_tr': 'Balık Saten Lüks Model 127',
                'name_sq': 'Modeli Sirenë Satin Pasuri 127',
                'summary_mk': 'Премиум русалка венчаница од екстра фин сатин',
                'summary_tr': 'Ekstra ince satindan premium balık gelinliği',
                'summary_sq': 'Modeli sirenë premium nga satin ultra i imët',
                'description_mk': 'Раскошна русалка венчаница од екстра фин сатин со мека допира. За невести што сакаат луксус.',
                'description_tr': 'Yumuşak dokunuş ile ekstra ince satindan yapılmış lüks balık gelinliği. Lüksü seven gelinler için.',
                'description_sq': 'Modeli i pasuri i sirenës i bërë nga satin ekstra i imët me preke të butë. Për nuset që dëshirojnë pasuri.',
                'category': 'mermaid',
            },
            {
                'model': 128,
                'name_mk': 'Минимал Асиметрична Модел 128',
                'name_tr': 'Minimal Asimetrik Model 128',
                'name_sq': 'Modeli Minimale Asimetrik 128',
                'summary_mk': 'Смела асиметрична минимална венчаница',
                'summary_tr': 'Cesur asimetrik minimal gelinliği',
                'summary_sq': 'Modeli minimal asimetrik i guximshëm',
                'description_mk': 'Модерна минимална венчаница со асиметричен дизајн што создаст динамичен изглед. За невести со авангардна апетита.',
                'description_tr': 'Dinamik bir görünüm yaratan asimetrik tasarımlı modern minimal gelinliği. Avangard zevke sahip gelinler için.',
                'description_sq': 'Modeli modern minimal me dizajn asimetrik që krijon një pamje dinamike. Për nuset me shije avangard.',
                'category': 'minimal',
            },
            {
                'model': 129,
                'name_mk': 'Класик Манила Модел 129',
                'name_tr': 'Klasik Manila Model 129',
                'name_sq': 'Modeli Klasik Manila 129',
                'summary_mk': 'Класична венчаница од естествена манила волокна',
                'summary_tr': 'Doğal manila fiber malzemeden klasik gelinliği',
                'summary_sq': 'Modeli klasik nga fibra e manilës natyrore',
                'description_mk': 'Еколошка класична венчаница од приватна манила волокна која е издржлива и еколошка. За свесни невести.',
                'description_tr': 'Dayanıklı ve ekolojik doğal manila fiber malzemeden yapılmış ekolojik klasik gelinliği. Bilinçli gelinler için.',
                'description_sq': 'Modeli klasik ekologjik i bërë nga fibra natyrore e manilës e cila është e qëndrueshme dhe ekologjike. Për nuset e ndërgjegjshme.',
                'category': 'classic',
            },
            {
                'model': 130,
                'name_mk': 'Принцеза Кристал Модел 130',
                'name_tr': 'Prenses Kristal Model 130',
                'name_sq': 'Modeli i Princeshës Kristal 130',
                'summary_mk': 'Раскошна принцеза венчаница со кристални украси',
                'summary_tr': 'Kristal süslemeli lüks prenses gelinliği',
                'summary_sq': 'Modeli i pasuri i princeshës me dekorime kristali',
                'description_mk': 'Раскошна принцеза венчаница со рачно постављени кристални украси што блещат магично. За невести што сакаат да светат.',
                'description_tr': 'Büyüleyici şekilde parlayan manuel kristal süslemeli lüks prenses gelinliği. Parlak görünmek isteyen gelinler için.',
                'description_sq': 'Modeli i pasuri i princeshës me dekorime kristali të vendosura dorazi që shkëlqejnë në mënyrë magjike. Për nuset që dëshirojnë të ndritshme.',
                'category': 'princess',
            },
        ]

        created_count = 0
        for product_data in products_data:
            model_num = product_data.pop('model')
            slug = f'model-{model_num}'
            
            product, created = Product.objects.get_or_create(
                slug=slug,
                defaults={
                    'name': product_data['name_mk'],
                    'name_tr': product_data['name_tr'],
                    'name_sq': product_data['name_sq'],
                    'summary': product_data['summary_mk'],
                    'summary_tr': product_data['summary_tr'],
                    'summary_sq': product_data['summary_sq'],
                    'description': product_data['description_mk'],
                    'description_tr': product_data['description_tr'],
                    'description_sq': product_data['description_sq'],
                    'category': product_data['category'],
                    'price': 'По договор',
                    'price_tr': 'Tafsiye Edilen Fiyat',
                    'price_sq': 'Me Marrëveshje',
                    'in_stock': True,
                    'is_featured': True,
                }
            )
            
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f'✓ Created: {product.name} (Model {model_num})')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'⚠ Already exists: {product.name} (Model {model_num})')
                )

        self.stdout.write(
            self.style.SUCCESS(f'\n✅ Import completed! {created_count} products created.')
        )
        self.stdout.write(
            self.style.SUCCESS(
                '\n📸 Image specifications:\n'
                '   - Recommended size: 600x800 pixels (3:4 vertical)\n'
                '   - Format: JPG or PNG\n'
                '   - Max file size: 400KB\n'
                '   - Upload from Django Admin > Products > Edit\n'
                '\n📱 Homepage & Portfolio:\n'
                '   - is_featured=True (Featured products on homepage)\n'
                '   - Portfolio: Add to "Dress Gallery" via PageMedia section\n'
            )
        )
