from django.core.management.base import BaseCommand
from core.models import FAQItem


class Command(BaseCommand):
    help = "Load FAQ items - all 3 languages (Macedonian, Albanian, Turkish)"

    def handle(self, *args, **options):
        faqs_data = [
            {
                "category": "Закажување термини и Проби",
                "order": 1,
                "question_mk": "Што треба да направам пред да дојдам на закажаниот термин?",
                "answer_mk": "Ви препорачуваме да изберете облека во која ќе можете удобно да се движите. Донесувањето на чевли со високи потпетици, долна облека во боја на кожа и неколку фотографии од модели што ви се допаѓаат ќе го олесни процесот на дизајнирање.",
                "question_tr": "Randevuya gelmeden önce ne yapmalıyım?",
                "answer_tr": "Randevuya gelirken rahatça hareket edebileceğiniz kıyafetler tercih etmenizi öneririz. Topuklu ayakkabı, ten rengi iç çamaşırı ve beğendiğiniz modellerden birkaç örnek fotoğraf getirmeniz tasarım sürecini kolaylaştırır.",
                "question_sq": "Çfarë duhet të bëj para se të vij në takim (randevu)?",
                "answer_sq": "Ju rekomandojmë të zgjidhni veshje me të cilat mund të lëvizni lirshëm. Veshja e këpucëve me taka, të brendshmeve në ngjyrë mishi (nude) dhe sjellja e disa fotove shembuj të modeleve që pëlqeni do ta lehtësojë procesin e dizajnit.",
            },
            {
                "category": "Закажување термини и Проби",
                "order": 2,
                "question_mk": "Колку трае пробата?",
                "answer_mk": "Секоја проба трае просечно 45-60 минути. Времето може да варира во зависност од деталите на дизајнот.",
                "question_tr": "Prova süresi ne kadar sürer?",
                "answer_tr": "Her prova ortalama 45–60 dakika sürer. Tasarımın detayına göre süre değişebilir.",
                "question_sq": "Sa zgjat prova?",
                "answer_sq": "Çdo provë zgjat mesatarisht 45-60 minuta. Koha mund të ndryshojë në varësi të detajeve të dizajnit.",
            },
            {
                "category": "Закажување термини и Проби",
                "order": 3,
                "question_mk": "Со колку луѓе можам да дојдам?",
                "answer_mk": "За да имате пријатно и удобно искуство, препорачуваме да дојдете со најмногу 2 гости (придружници).",
                "question_tr": "Kaç kişi ile gelebilirim?",
                "answer_tr": "Rahat bir deneyim yaşayabilmeniz için maksimum 2 misafir ile gelmenizi öneriyoruz.",
                "question_sq": "Me sa persona mund të vij?",
                "answer_sq": "Për të pasur një përvojë sa më të rehatshme, ju rekomandojmë të vini me maksimumi 2 shoqërues (mysafirë).",
                "question_mk": "Дали можам да го откажам или одложам терминот?",
                "answer_mk": "Да, можете бесплатно да го одложите или откажете терминот доколку не известите најмалку 24 часа однапред.",
                "question_tr": "Randevumu iptal edebilir veya erteleyebilir miyim?",
                "answer_tr": "Evet, randevunuzu en az 24 saat önce haber vererek ücretsiz olarak erteleyebilir veya iptal edebilirsiniz.",
                "question_sq": "A mund ta anuloj ose ta shtyj takimin?",
                "answer_sq": "Po, mund ta shtyni ose anuloni takimin tuaj pa pagesë duke na njoftuar të paktën 24 orë përpara.",
                "question_mk": "Дали венчаницата ќе се шие точно по мои мерки?",
                "answer_mk": "Да. Сите наши венчаници се произведуваат од нула со земање на лични мерки специјално за вас. Не се користат готови калапи или стандардни големини.",
                "question_tr": "Gelinliğim tam ölçüme göre mi dikilecek?",
                "answer_tr": "Evet. Tüm gelinliklerimiz kişiye özel ölçü alınarak sıfırdan üretilir. Hazır kalıp veya standart beden kullanılmaz.",
                "question_sq": "A do të qepet fustani im i nusërisë saktësisht sipas masave të mia?",
                "answer_sq": "Po. Të gjitha fustanet tona të nusërisë prodhohen nga e para duke marrë masa personale. Nuk përdoren kallëpe të gatshme ose masa standarde.",
                "question_mk": "Можам ли да правам измени во дизајнот?",
                "answer_mk": "Да. За време на процесот на дизајнирање можни се промени на деколтето, ракавите, должината на здолништето, линијата на струкот и други детали. За поголеми измени може да се примени дополнителен надомест.",
                "question_tr": "Tasarımda değişiklik yapabilir miyim?",
                "answer_tr": "Evet. Yaka, kol, etek boyu, bel hattı ve detay değişiklikleri tasarım sürecinde mümkündür. Büyük değişiklikler için ek ücret uygulanabilir.",
                "question_sq": "A mund të bëj ndryshime në dizajn?",
                "answer_sq": "Po. Ndryshimet në jakë, mëngë, gjatësinë e fundit, linjën e belit dhe detaje të tjera janë të mundshme gjatë procesit të dizajnit. Për ndryshime të mëdha mund të aplikohet tarifë shtesë.",
                "question_mk": "Дали правите проба со прототип или мостра?",
                "answer_mk": "Во случаи кога е потребно, подготвуваме toile (пробен модел) за да се осигуриме дека моделот правилно ќе легне на вашето тело.",
                "question_tr": "Prototip veya numune prova yapıyor musunuz?",
                "answer_tr": "Gerekli durumlarda modelin vücutta doğru oturması için toile (numune prova) hazırlıyoruz.",
                "question_sq": "A bëni prova me prototip ose mostër?",
                "answer_sq": "Në rastet kur është e nevojshme, ne përgatisim një toile (provë mostër) për t'u siguruar që modeli të rrijë saktë në trup.",
                "question_mk": "За колку време се подготвува венчаница по нарачка (специјално шиење)?",
                "answer_mk": "Обично процесот трае помеѓу 6 и 12 недели. За подетални и сложени модели, времето може да биде подолго.",
                "question_tr": "Özel dikim gelinlik ne kadar sürede hazırlanır?",
                "answer_tr": "Genellikle 6–12 hafta arası sürmektedir. Daha detaylı modeller için süre uzayabilir.",
                "question_sq": "Sa kohë duhet për të përgatitur një fustan nusërie me qepje të posaçme?",
                "answer_sq": "Zakonisht zgjat nga 6 deri në 12 javë. Për modele më të detajuara koha mund të zgjatet.",
                "question_mk": "Дали прифаќате итни нарачки?",
                "answer_mk": "Да, имаме услуга за експресно (брзо) производство. Во зависност од моделот и достапноста на ткаенината, венчаницата може да биде испорачана во рок од 2-4 недели.",
                "question_tr": "Acele sipariş alıyor musunuz?",
                "answer_tr": "Evet, express (hızlı) üretim hizmetimiz mevcuttur. Model ve kumaş uygunluğuna göre 2–4 hafta içinde teslim edilebilir.",
                "question_sq": "A pranoni porosi urgjente?",
                "answer_sq": "Po, kemi shërbimin e prodhimit express (të shpejtë). Në varësi të modelit dhe disponueshmërisë së pëlhurës, mund të dorëzohet brenda 2-4 javësh.",
                "question_mk": "Дали е потребен депозит за нарачка?",
                "answer_mk": "Да. За да започне процесот на специјално шиење, се наплаќа 30% од вкупната сума како депозит.",
                "question_tr": "Sipariş için depozito gerekiyor mu?",
                "answer_tr": "Evet. Özel dikim sürecini başlatmak için toplam ücretin %30'u depozito olarak alınır.",
                "question_sq": "A kërkohet paradhënie (depozitë) për porosinë?",
                "answer_sq": "Po. Për të filluar procesin e qepjes speciale, merret 30% e shumës totale si paradhënie.",
                "question_mk": "Дали се враќа депозитот?",
                "answer_mk": "Бидејќи процесите на специјално шиење се персонализирани (изработени по мерка), депозитот не се враќа. Сепак, промените на термините за проба се бесплатни.",
                "question_tr": "Depozito iadesi var mı?",
                "answer_tr": "Özel dikim süreçleri kişiye özel olduğu için depozito iadesi yapılmaz. Ancak randevu değişiklikleri ücretsizdir.",
                "question_sq": "A ka rimbursim të paradhënies?",
                "answer_sq": "Meqenëse proceset e qepjes speciale janë personale, paradhënia nuk kthehet. Megjithatë, ndryshimet e datave të takimeve janë falas.",
                "question_mk": "Колку проби се прават?",
                "answer_mk": "Стандардно се прават 3-4 проби. Во нашиот пакет за Premium услуги нудиме опција за неограничен број проби.",
                "question_tr": "Kaç prova yapılıyor?",
                "answer_tr": "Standart olarak 3–4 prova yapılır. Premium hizmet paketimizde sınırsız prova seçeneği sunulmaktadır.",
                "question_sq": "Sa prova bëhen?",
                "answer_sq": "Si standard bëhen 3-4 prova. Në paketën tonë të shërbimit Premium ofrohet opsioni i provave pa limit.",
                "question_mk": "Може ли да направите промени во последен момент?",
                "answer_mk": "Се трудиме да помогнеме секогаш кога е можно, но доколку измената влијае на структурата на моделот, може да биде потребно дополнително време и надомест.",
                "question_tr": "Son dakika değişiklikleri yapabilir misiniz?",
                "answer_tr": "Mümkün olduğunda yardımcı oluyoruz ancak değişiklik modeli etkiliyorsa ek süre ve ücret gerekebilir.",
                "question_sq": "A mund të bëni ndryshime të minutës së fundit?",
                "answer_sq": "Ne ndihmojmë kur është e mundur, por nëse ndryshimi ndikon në strukturën e modelit, mund të kërkohet kohë dhe tarifë shtesë.",
                "question_mk": "Како се врши испораката на венчаницата?",
                "answer_mk": "Испораката се врши по последната проба, во специјална заштитна торба. Доколку сакате, пред испораката бесплатно ја применуваме услугата за пареа / пеглање.",
                "question_tr": "Gelinlik teslimi nasıl oluyor?",
                "answer_tr": "Gelinlik teslimi, son provadan sonra özel koruma çantası içinde yapılır. Dilerseniz teslim öncesi buharlama / ütüleme hizmeti ücretsiz uygulanır.",
                "question_sq": "Si bëhet dorëzimi i fustanit të nusërisë?",
                "answer_sq": "Dorëzimi i fustanit bëhet pas provës së fundit, brenda një çante të posaçme mbrojtëse. Nëse dëshironi, shërbimi i hekurosjes me avull aplikohet falas para dorëzimit.",
                "question_mk": "Како да ја чувам венчаницата?",
                "answer_mk": "Ви препорачуваме да ја чувате на ладно и суво место, подалеку од директна сончева светлина. Можете да ја чувате во специјалната заштитна торба што ви ја даваме.",
                "question_tr": "Gelinliği nasıl saklamalıyım?",
                "answer_tr": "Doğrudan güneş almayan, serin ve kuru bir yerde saklamanızı öneririz. Size verilen özel koruma çantası ile muhafaza edebilirsiniz.",
                "question_sq": "Si duhet ta ruaj fustanin e nusërisë?",
                "answer_sq": "Ju rekomandojmë ta ruani në një vend të freskët dhe të thatë, larg dritës së drejtpërdrejtë të diellit. Mund ta ruani me çantën speciale mbrojtëse që ju është dhënë.",
                "question_mk": "Кои видови ткаенини се достапни?",
                "answer_mk": "Во нашето ателје располагаме со многу премиум ткаенини како сатен, микадо, шифон, тул, француска чипка и органза.",
                "question_tr": "Hangi kumaş türleri mevcut?",
                "answer_tr": "Atölyemizde saten, mikado, şifon, tül, Fransız danteli ve organze gibi birçok premium kumaş çeşidi mevcuttur.",
                "question_sq": "Çfarë lloje pëlhurash keni?",
                "answer_sq": "Në atelienë tonë disponohen shumë lloje pëlhurash premium si saten, mikado, shifon, tyl, dantellë franceze dhe organza.",
                "question_mk": "Дали изработувате венчаници во големи броеви (plus-size)?",
                "answer_mk": "Да, шиеме венчаници целосно по мерка за сите големини на тело.",
                "question_tr": "Plus-size (büyük beden) gelinlik yapıyor musunuz?",
                "answer_tr": "Evet, tüm bedenler için tamamen ölçüye özel gelinlik dikiyoruz.",
                "question_sq": "A bëni fustane nusërie për masa të mëdha (plus-size)?",
                "answer_sq": "Po, ne qepim fustane nusërie plotësisht sipas masave për të gjitha madhësitë e trupit.",
                "question_mk": "Можеме ли да направиме онлајн консултација?",
                "answer_mk": "Да. За невестите кои се надвор од градот, нудиме услуга за онлајн советување за дизајн.",
                "question_tr": "Online görüşme yapabilir miyiz?",
                "answer_tr": "Evet. Şehir dışında olan gelinler için online tasarım danışmanlığı hizmetimiz mevcuttur.",
                "question_sq": "A mund të bëjmë takim online?",
                "answer_sq": "Po. Për nuset që janë jashtë qytetit, kemi shërbimin e konsulencës së dizajnit online.",
                "question_mk": "Каде се наоѓа вашето ателје?",
                "answer_mk": "Адреса: Samoilova 90, Skopje Kale, Makedonija. Доколку сакате, можеме да додадеме и линк до мапата.",
                "question_tr": "Atölyeniz nerede?",
                "answer_tr": "Adres bölümünüz burada yazılır. Dilerseniz harita bağlantısı da ekleyebiliriz.",
                "question_sq": "Ku ndodhet atelieja juaj?",
                "answer_sq": "Adresa: Samoilova 90, Skopje Kale, Maqedoni. Nëse dëshironi, mund të shtojmë edhe linkun e hartës.",
                "question_mk": "Дали има паркинг?",
                "answer_mk": "Во близина на нашето ателје има место за паркирање. Деталите ги испраќаме во пораката за потврда на терминот.",
                "question_tr": "Park yeri mevcut mu?",
                "answer_tr": "Atölyemize yakın bölgede park yeri bulunmaktadır. Detayları randevu onay mesajında iletiyoruz.",
                "question_sq": "A ka vendparkim?",
                "answer_sq": "Ka vendparkim në zonën afër ateliesë sonë. Detajet jua dërgojmë në mesazhin e konfirmimit të takimit.",
            },
            {
                "category": "Закажување термини и Проби",
                "order": 21,
                "question_mk": "Дали моите клиентски податоци се безбедни?",
                "answer_mk": "Да. Сите ваши лични податоци и мерки се чуваат доверливо во согласност со законите за заштита на лични податоци и не се споделуваат со трети лица.",
                "question_tr": "Müşteri bilgilerim güvende mi?",
                "answer_tr": "Evet. Tüm kişisel verileriniz ve ölçüleriniz KVKK'ya uygun şekilde gizli olarak saklanır ve üçüncü kişilerle paylaşılmaz.",
                "question_sq": "A janë të sigurta të dhënat e mia personale?",
                "answer_sq": "Po. Të gjitha të dhënat tuaja personale dhe masat ruhen në mënyrë konfidenciale sipas ligjeve për mbrojtjen e të dhënave dhe nuk ndahen me palë të treta.",
            },
            {
                "category": "Закажување термини и Проби",
                "order": 22,
                "question_mk": "Може ли да видам венчаници што сте ги сошиле претходно?",
                "answer_mk": "Да, на нашата веб-страница и на нашиот Instagram профил можете да видите фотографии од нашите вистински невести.",
                "question_tr": "Daha önce diktiğiniz gelinlikleri görebilir miyim?",
                "answer_tr": "Evet, web sitemizde ve Instagram hesabımızda gerçek gelinlerimizin fotoğraflarını görebilirsiniz.",
                "question_sq": "A mund t'i shoh fustanet që keni qepur më parë?",
                "answer_sq": "Po, mund të shihni fotot e nuseve tona reale në faqen tonë të internetit dhe në llogarinë tonë të Instagramit.",
            },
        ]

        # Clear existing FAQs
        FAQItem.objects.all().delete()
        
        # Create FAQs
        created_count = 0
        for faq_data in faqs_data:
            faq = FAQItem.objects.create(**faq_data)
            created_count += 1
        
        self.stdout.write(
            self.style.SUCCESS(f"Uspesno ucitani {created_count} FAQ stavki na site 3 jazika - Makedonski, Albanski, Turski")
        )
