# Generated by Django 5.0.4 on 2025-12-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pricingpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for this content', max_length=100, unique=True)),
                ('content_mk', models.TextField(verbose_name='Содржина (Македонски)')),
                ('content_tr', models.TextField(blank=True, verbose_name='İçerik (Türkçe)')),
                ('content_sq', models.TextField(blank=True, verbose_name='Përmbajtja (Shqip)')),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Contents',
            },
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='features_sq',
            field=models.TextField(blank=True, verbose_name='Veçoritë (Shqip)'),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='features_tr',
            field=models.TextField(blank=True, verbose_name='Özellikler (Türkçe)'),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='name_sq',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emri (Shqip)'),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='name_tr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ad (Türkçe)'),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='period_sq',
            field=models.CharField(blank=True, max_length=50, verbose_name='Periudha (Shqip)'),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='period_tr',
            field=models.CharField(blank=True, max_length=50, verbose_name='Periyot (Türkçe)'),
        ),
    ]
