# Generated by Django 5.0.4 on 2025-12-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitecontent_pricingpackage_features_sq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ankora Atelier', max_length=100)),
                ('tagline', models.CharField(default='Bridal & Couture Studio', max_length=200)),
                ('color_primary', models.CharField(default='#fef1eb', help_text='Background color (hex)', max_length=7)),
                ('color_secondary', models.CharField(default='#191919', help_text='Main text color (hex)', max_length=7)),
                ('color_accent', models.CharField(default='#d86a5f', help_text='Accent/button color (hex)', max_length=7)),
                ('color_accent_dark', models.CharField(default='#a84334', help_text='Accent hover color (hex)', max_length=7)),
                ('color_text_soft', models.CharField(default='#6c6c6c', help_text='Secondary text color (hex)', max_length=7)),
                ('address', models.TextField(blank=True, default='Pariser Platz 3, 10117 Berlin')),
                ('email', models.EmailField(blank=True, default='atelier@ankora.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+49 30 1234 5678', max_length=30)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
