# Generated by Django 5.0.4 on 2025-12-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Virgülle ayırarak etiketler girin', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='designer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tasarımcı'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='features',
            field=models.TextField(blank=True, help_text='Her satıra bir özellik yazın', verbose_name='Özellikler'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='year',
            field=models.CharField(blank=True, default='2024', max_length=10, verbose_name='Yıl'),
        ),
    ]
