# Generated by Django 5.0.4 on 2025-12-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogpost_likes_blogpost_tags_portfolioitem_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO açıklaması (max 160 karakter)', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO başlığı (max 70 karakter, boş bırakılırsa title kullanılır)', max_length=70),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO açıklaması (max 160 karakter)', max_length=160),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO başlığı (max 70 karakter, boş bırakılırsa title kullanılır)', max_length=70),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.URLField(blank=True, help_text="Favicon URL'si (Önerilen boyut: 32x32 piksel)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, default='', help_text="Footer'da görünecek ek metin"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text="Logo resmi URL'si (Önerilen boyut: 200x60 piksel)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Site açıklaması (SEO için, max 160 karakter)', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Anahtar kelimeler, virgülle ayırın', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pinterest_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=1200&q=80', help_text='Önerilen boyut: 1200x675 piksel (16:9 yatay dikdörtgen)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80', help_text='Önerilen boyut: 1200x800 piksel (yatay dikdörtgen)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', help_text='Önerilen boyut: 600x800 piksel (dikey dikdörtgen)'),
        ),
    ]
