# Generated by Django 5.0.4 on 2025-12-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogpost_meta_description_blogpost_meta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_home', 'Anasayfa Hero'), ('hero_home_2', 'Anasayfa Hero 2'), ('about_hero', 'Hakkımızda Hero'), ('about_section', 'Hakkımızda Section'), ('services_banner', 'Hizmetler Banner'), ('services_gallery', 'Hizmetler Galerisi'), ('contact_gallery', 'İletişim Galerisi'), ('bride_gallery', 'Gelin Galerisi'), ('faq_accommodation', 'SSS Konaklama'), ('rsvp_hero', 'RSVP Hero'), ('portfolio_showcase', 'Portfolio Showcase'), ('mini_gallery', 'Mini Galeri')], max_length=50)),
                ('image', models.ImageField(help_text='Sayfa resmi', upload_to='page_media/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Görüntüleme sırası')),
            ],
            options={
                'verbose_name': 'Page Media',
                'verbose_name_plural': 'Page Media',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_home_title', 'Anasayfa Hero Başlık'), ('hero_home_subtitle', 'Anasayfa Hero Alt Başlık'), ('hero_home_desc', 'Anasayfa Hero Açıklama'), ('hero_home_hours', 'Anasayfa Çalışma Saatleri'), ('hero2_title', 'Hero 2 Başlık'), ('hero2_desc', 'Hero 2 Açıklama'), ('about_title', 'Hakkımızda Başlık'), ('about_desc', 'Hakkımızda Açıklama'), ('about_hours', 'Hakkımızda Çalışma Saatleri'), ('faq_questions', 'SSS Soruları'), ('rsvp_title', 'RSVP Başlık'), ('rsvp_desc', 'RSVP Açıklama')], max_length=50, unique=True)),
                ('content_mk', models.TextField(verbose_name='İçerik (Македонски)')),
                ('content_tr', models.TextField(blank=True, verbose_name='İçerik (Türkçe)')),
                ('content_sq', models.TextField(blank=True, verbose_name='Përmbajtja (Shqip)')),
            ],
            options={
                'verbose_name': 'Page Text',
                'verbose_name_plural': 'Page Texts',
            },
        ),
        migrations.CreateModel(
            name='VideoEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'Anasayfa'), ('about', 'Hakkımızda'), ('services', 'Hizmetler')], max_length=20, unique=True)),
                ('youtube_id', models.CharField(help_text="YouTube video ID (url'nin ?v= sonrası)", max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Video Embed',
                'verbose_name_plural': 'Video Embeds',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_file',
            field=models.FileField(blank=True, help_text='Favicon dosyası (Önerilen boyut: 32x32 piksel, .ico formatında)', null=True, upload_to='favicons/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Logo resmi (Önerilen boyut: 200x60 piksel)', null=True, upload_to='logos/'),
        ),
    ]
