# Generated by Django 5.0.4 on 2025-12-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pagemedia_pagetext_videoembed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_mk',
            field=models.CharField(blank=True, default='© 2025 Naba Studio by Semma. Сите права се задржаа.', help_text='Copyright text (Macedonian)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_sq',
            field=models.CharField(blank=True, default='© 2025 Naba Studio by Semma. Të gjitha të drejtat e rezervuara.', help_text='Copyright text (Albanian)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_tr',
            field=models.CharField(blank=True, default='© 2025 Naba Studio by Semma. Tüm Hakları Saklıdır.', help_text='Copyright text (Turkish)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='Samoilova 90, Skopje Kale'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='nabastudio25@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='070 666 567', max_length=30),
        ),
    ]
