# Generated by Django 5.0.4 on 2025-12-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_copyright_text_mk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Google Maps embed kod. iframe src kısmını yapıştır. Otomatik iframe oluşturuluyorsa boş bırak'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_latitude',
            field=models.DecimalField(decimal_places=6, default='41.997335', help_text='Harita enlemi (latitude)', max_digits=9),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_longitude',
            field=models.DecimalField(decimal_places=6, default='21.428057', help_text='Harita boylamı (longitude)', max_digits=9),
        ),
    ]
