# Generated by Django 5.0.4 on 2025-12-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_map_embed_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Google Maps embed kod. Boş bırakılırsa koordinatlardan otomatik oluşturulur.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_latitude',
            field=models.DecimalField(decimal_places=6, default='41.997335', help_text='Naba Studio Samoilova 90 enlemi: 41.997335', max_digits=9),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_longitude',
            field=models.DecimalField(decimal_places=6, default='21.428057', help_text='Naba Studio Samoilova 90 boylamı: 21.428057', max_digits=9),
        ),
    ]
