# Generated by Django 5.0.4 on 2025-12-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sitesettings_map_embed_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Google Maps embed kod: https://maps.app.goo.gl/TnBQbTKjQFpx3DFN7'),
        ),
    ]
