# Generated by Django 5.0.4 on 2025-12-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sitesettings_map_embed_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['category', 'order']},
        ),
        migrations.RenameField(
            model_name='faqitem',
            old_name='answer',
            new_name='answer_mk',
        ),
        migrations.RenameField(
            model_name='faqitem',
            old_name='question',
            new_name='question_mk',
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_sq',
            field=models.TextField(blank=True, verbose_name='Përgjigja (Shqip)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_tr',
            field=models.TextField(blank=True, verbose_name='Cevap (Türkçe)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='category',
            field=models.CharField(default='General', help_text='Kategorija / Category / Kategori', max_length=100),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_sq',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pyetja (Shqip)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_tr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Soru (Türkçe)'),
        ),
    ]
