# Generated by Django 5.0.4 on 2025-12-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_faqitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='category',
            field=models.CharField(choices=[('Booking & Trials', 'Booking & Trials'), ('Design & Customization', 'Design & Customization'), ('Timeline & Pricing', 'Timeline & Pricing'), ('Delivery & Care', 'Delivery & Care'), ('Products & Materials', 'Products & Materials'), ('Contact & Information', 'Contact & Information')], default='Booking & Trials', help_text='Kategorija / Category / Kategori', max_length=100),
        ),
    ]
