# Generated by Django 5.0.4 on 2025-12-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_faqitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_tr', models.CharField(blank=True, max_length=100, verbose_name='Ad (Türkçe)')),
                ('name_sq', models.CharField(blank=True, max_length=100, verbose_name='Emri (Shqip)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, verbose_name='Açıklama (Türkçe)')),
                ('description_sq', models.TextField(blank=True, verbose_name='Përshkrimi (Shqip)')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='Fiyat (Opsiyonel)')),
                ('icon', models.CharField(default='✨', help_text='Emoji ikon (ör: ✨, 🎨, 📏, 👗, ⚡, 🎁, ✂️, 🧵, ♨️, 📦, 💻)', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
