# Generated by Django 5.0.4 on 2025-12-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_addonservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Gelinlik Tasarımları', 'Gelinlik Tasarımları'), ('Kişisel Hikayeler', 'Kişisel Hikayeler'), ('Moda Trendleri', 'Moda Trendleri'), ('Bakım & Tavsiyeleri', 'Bakım & Tavsiyeleri'), ('Atelier Haberleri', 'Atelier Haberleri')], default='Atelier Haberleri', help_text='Blog yazısının kategorisini seçin', max_length=100),
        ),
    ]
