# Generated by Django 5.0.4 on 2025-12-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemedia',
            options={'ordering': ['section', 'order'], 'verbose_name': 'Sayfa Görseli', 'verbose_name_plural': 'Sayfa Görselleri'},
        ),
        migrations.AddField(
            model_name='pagemedia',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Görselin açıklaması (görsel yüklenemediğinde gösterilir)', max_length=200, verbose_name='Alt Text (SEO & Erişilebilirlik)'),
        ),
        migrations.AddField(
            model_name='pagemedia',
            name='description',
            field=models.TextField(blank=True, help_text='Bu görsel için gerekli boyut ve formatı belirtin. Örn: 1200x800px, JPG, max 500KB', verbose_name='Ölçüler & Format Bilgisi'),
        ),
        migrations.AddField(
            model_name='pagemedia',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Pasif görseller sayfada gösterilmez', verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='pagemedia',
            name='title',
            field=models.CharField(blank=True, help_text='Bu görsele ait açıklayıcı başlık (opsiyonel)', max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='image',
            field=models.ImageField(help_text='Görsel dosyasını yükleyin (.jpg, .png, .webp)', upload_to='page_media/'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Aynı bölümde birden çok görsel varsa görüntülenme sırası', verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='section',
            field=models.CharField(choices=[('hero_home', 'Anasayfa - Hero 1 Arka Planı'), ('hero_home_2', 'Anasayfa - Hero 2 Arka Planı'), ('hero_home_stack_1', 'Anasayfa - Hero 2 Stack Resim 1'), ('hero_home_stack_2', 'Anasayfa - Hero 2 Stack Resim 2'), ('hero_home_floral', 'Anasayfa - Hero 2 Çiçek Dekorasyon'), ('dress_gallery_mini_1', 'Anasayfa - Dress Gallery Mini Resim 1'), ('dress_gallery_mini_2', 'Anasayfa - Dress Gallery Mini Resim 2'), ('dress_gallery_mini_3', 'Anasayfa - Dress Gallery Mini Resim 3'), ('bride_gallery_1', 'Anasayfa - Gelin Galerisi Resim 1'), ('bride_gallery_2', 'Anasayfa - Gelin Galerisi Resim 2'), ('bride_gallery_3', 'Anasayfa - Gelin Galerisi Resim 3'), ('bride_gallery_4', 'Anasayfa - Gelin Galerisi Resim 4'), ('bride_gallery_5', 'Anasayfa - Gelin Galerisi Resim 5'), ('about_hero', 'Hakkımızda - Hero Arka Planı'), ('services_banner', 'Hizmetler - Banner Arka Planı'), ('contact_gallery', 'İletişim - Galeri Resimleri'), ('faq_accommodation', 'SSS - Konaklama Resimleri'), ('portfolio_showcase', 'Portfolio - Galerideki Resimler'), ('rsvp_hero', 'RSVP - Hero Arka Planı')], max_length=50, verbose_name='Bölüm'),
        ),
        migrations.AlterUniqueTogether(
            name='pagemedia',
            unique_together={('section', 'order')},
        ),
    ]
