# Generated by Django 5.0.4 on 2025-12-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_pagemedia_options_pagemedia_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A Kesim', 'A Kesim'), ('Prenses', 'Prenses'), ('Balık', 'Balık'), ('Minimal', 'Minimal'), ('Klasik', 'Klasik')], default='A Kesim', max_length=50, verbose_name='Kategori'),
        ),
    ]
