# Generated by Django 5.0.4 on 2025-12-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Email gönderimini aktif et'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, help_text='Gönderen email adresi (genellikle SMTP kullanıcısı ile aynı)', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(default='smtp.gmail.com', help_text='SMTP sunucu adresi (Gmail: smtp.gmail.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP şifresi (Gmail App Password)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='SMTP port numarası (Gmail TLS: 587)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='TLS kullan (Gmail için True)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_user',
            field=models.EmailField(blank=True, help_text='SMTP kullanıcı adı (Gmail adresi)', max_length=254),
        ),
    ]
