# Generated by Django 5.0.4 on 2025-12-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_blogpost_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_sq',
            field=models.TextField(blank=True, verbose_name='Përmbajtja (Shqip)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_tr',
            field=models.TextField(blank=True, verbose_name='İçerik (Türkçe)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_sq',
            field=models.TextField(blank=True, verbose_name='Përmbledhja (Shqip)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_tr',
            field=models.TextField(blank=True, verbose_name='Özet (Türkçe)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_sq',
            field=models.CharField(blank=True, max_length=160, verbose_name='Titulli (Shqip)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_tr',
            field=models.CharField(blank=True, max_length=160, verbose_name='Başlık (Türkçe)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(verbose_name='Содржина (Македонски)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('bridal_designs', 'Дизајни за невести / Gelinlik Tasarımları / Dizajne për nuse'), ('personal_stories', 'Лични приказни / Kişisel Hikayeler / Histori personale'), ('fashion_trends', 'Модни трендови / Moda Trendleri / Trendet e modës'), ('care_tips', 'Совети за нега / Bakım Tavsiyeleri / Këshilla për kujdes'), ('atelier_news', 'Вести од атељето / Atelier Haberleri / Lajme nga atelieja')], default='atelier_news', help_text='Blog yazısının kategorisini seçin', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(verbose_name='Извадок (Македонски)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Наслов (Македонски)'),
        ),
    ]
