# Generated by Django 5.0.4 on 2025-12-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_blogpost_body_sq_blogpost_body_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonservice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис (Македонски)'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Име (Македонски)'),
        ),
    ]
