# Generated by Django 5.0.4 on 2025-12-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_addonservice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='description_sq',
            field=models.TextField(blank=True, verbose_name='Përshkrimi (Shqip)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_tr',
            field=models.TextField(blank=True, verbose_name='Açıklama (Türkçe)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='summary_sq',
            field=models.CharField(blank=True, max_length=200, verbose_name='Përmbledhja (Shqip)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='summary_tr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Özet (Türkçe)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_sq',
            field=models.CharField(blank=True, max_length=120, verbose_name='Titulli (Shqip)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_tr',
            field=models.CharField(blank=True, max_length=120, verbose_name='Başlık (Türkçe)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sq',
            field=models.TextField(blank=True, verbose_name='Përshkrimi (Shqip)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(blank=True, verbose_name='Açıklama (Türkçe)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sq',
            field=models.CharField(blank=True, max_length=120, verbose_name='Emri (Shqip)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tr',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ad (Türkçe)'),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_sq',
            field=models.CharField(blank=True, max_length=200, verbose_name='Përmbledhja (Shqip)'),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_tr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Özet (Türkçe)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_sq',
            field=models.TextField(blank=True, verbose_name='Përshkrimi (Shqip)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_tr',
            field=models.TextField(blank=True, verbose_name='Açıklama (Türkçe)'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_sq',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nëntitulli (Shqip)'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=150, verbose_name='Alt Başlık (Türkçe)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_sq',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulli (Shqip)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_tr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Başlık (Türkçe)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer_mk',
            field=models.TextField(verbose_name='Одговор (Македонски)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='category',
            field=models.CharField(choices=[('booking_trials', 'Резервации и проби / Rezervasyon ve Deneme / Rezervime dhe prova'), ('design_customization', 'Дизајн и прилагодување / Tasarım ve Özelleştirme / Dizajn dhe personalizim'), ('timeline_pricing', 'Рокови и цени / Süre ve Fiyatlandırma / Afatet dhe çmimet'), ('delivery_care', 'Достава и нега / Teslimat ve Bakım / Dorëzimi dhe kujdesi'), ('products_materials', 'Производи и материјали / Ürünler ve Malzemeler / Produkte dhe materiale'), ('contact_info', 'Контакт и информации / İletişim ve Bilgi / Kontakt dhe informacion')], default='booking_trials', help_text='Категорија / Kategori / Kategoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_mk',
            field=models.CharField(max_length=200, verbose_name='Прашање (Македонски)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(verbose_name='Опис (Македонски)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='designer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дизајнер'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='features',
            field=models.TextField(blank=True, help_text='Her satıra bir özellik yazın', verbose_name='Карактеристики'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='Резиме (Македонски)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Наслов (Македонски)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='year',
            field=models.CharField(blank=True, default='2024', max_length=10, verbose_name='Година'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('a_line', 'А-линија / A Kesim / A-linjë'), ('princess', 'Принцеза / Prenses / Princeshë'), ('mermaid', 'Русалка / Balık / Sirenë'), ('minimal', 'Минимал / Minimal / Minimale'), ('classic', 'Класик / Klasik / Klasike')], default='a_line', max_length=50, verbose_name='Категорија'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Опис (Македонски)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Име (Македонски)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='По договор', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='Резиме (Македонски)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Опис (Македонски)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Поднаслов (Македонски)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наслов (Македонски)'),
        ),
    ]
