# Generated by Django 5.0.4 on 2025-12-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_portfolioitem_description_sq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonservice',
            name='price_sq',
            field=models.CharField(blank=True, help_text='P.sh: FALAS, 500 den, Me marrëveshje', max_length=50, verbose_name='Çmimi (Shqip)'),
        ),
        migrations.AddField(
            model_name='addonservice',
            name='price_tr',
            field=models.CharField(blank=True, help_text='Ör: ÜCRETSİZ, 500 TL, Fiyat sorunuz', max_length=50, verbose_name='Fiyat (Türkçe)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_sq',
            field=models.CharField(blank=True, help_text='Max 160 karaktere', max_length=160, verbose_name='SEO Përshkrimi (Shqip)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_tr',
            field=models.CharField(blank=True, help_text='Max 160 karakter', max_length=160, verbose_name='SEO Açıklama (Türkçe)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_sq',
            field=models.CharField(blank=True, help_text='Max 70 karaktere', max_length=70, verbose_name='SEO Titulli (Shqip)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_tr',
            field=models.CharField(blank=True, help_text='Max 70 karakter', max_length=70, verbose_name='SEO Başlık (Türkçe)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_description_sq',
            field=models.CharField(blank=True, help_text='Max 160 karaktere', max_length=160, verbose_name='SEO Përshkrimi (Shqip)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_description_tr',
            field=models.CharField(blank=True, help_text='Max 160 karakter', max_length=160, verbose_name='SEO Açıklama (Türkçe)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_title_sq',
            field=models.CharField(blank=True, help_text='Max 70 karaktere', max_length=70, verbose_name='SEO Titulli (Shqip)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_title_tr',
            field=models.CharField(blank=True, help_text='Max 70 karakter', max_length=70, verbose_name='SEO Başlık (Türkçe)'),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='price',
            field=models.CharField(blank=True, help_text='Пр: БЕСПЛАТНО, 500 ден, По договор', max_length=50, verbose_name='Цена (Македонски)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Max 160 карактери', max_length=160, verbose_name='SEO Опис (Македонски)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Max 70 карактери', max_length=70, verbose_name='SEO Наслов (Македонски)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='category',
            field=models.CharField(choices=[('booking_trials', 'Резервации и проби'), ('design_customization', 'Дизајн и прилагодување'), ('timeline_pricing', 'Рокови и цени'), ('delivery_care', 'Достава и нега'), ('products_materials', 'Производи и материјали'), ('contact_info', 'Контакт и информации')], default='booking_trials', help_text='Категорија / Kategori / Kategoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Max 160 карактери', max_length=160, verbose_name='SEO Опис (Македонски)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Max 70 карактери', max_length=70, verbose_name='SEO Наслов (Македонски)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('a_line', 'А-линија'), ('princess', 'Принцеза'), ('mermaid', 'Русалка'), ('minimal', 'Минимал'), ('classic', 'Класик')], default='a_line', max_length=50, verbose_name='Категорија'),
        ),
    ]
