# Generated by Django 5.0.4 on 2025-12-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_addonservice_price_sq_addonservice_price_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('bridal_designs', 'Дизајни за невести'), ('personal_stories', 'Лични приказни'), ('fashion_trends', 'Модни трендови'), ('care_tips', 'Совети за нега'), ('atelier_news', 'Вести од атељето')], default='atelier_news', help_text='Blog yazısının kategorisini seçin', max_length=100),
        ),
    ]
