# Generated by Django 5.0.4 on 2025-12-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-created_at', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Означете за да се прикаже на почетната страница (максимум 3)', verbose_name='Истакнат на почетна'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Препорачана големина: 600x800 пиксели (вертикален правоаголник)', upload_to='products/')),
                ('is_primary', models.BooleanField(default=False, help_text='Оваа слика ќе се прикаже како главна', verbose_name='Примарна слика')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Редослед')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product')),
            ],
            options={
                'verbose_name': 'Слика на производ',
                'verbose_name_plural': 'Слики на производи',
                'ordering': ['-is_primary', 'order'],
            },
        ),
    ]
