# Generated by Django 5.0.4 on 2025-12-25 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_product_options_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='38970666567', help_text='WhatsApp numarası (ülke kodu ile, boşluksuz: örn. 38970666567)', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.5, '0.5 ⭐'), (1.0, '1 ⭐'), (1.5, '1.5 ⭐'), (2.0, '2 ⭐'), (2.5, '2.5 ⭐'), (3.0, '3 ⭐'), (3.5, '3.5 ⭐'), (4.0, '4 ⭐'), (4.5, '4.5 ⭐'), (5.0, '5 ⭐')], decimal_places=1, max_digits=2, verbose_name='Değerlendirme')),
                ('reviewer_name', models.CharField(max_length=100, verbose_name='İsim')),
                ('reviewer_email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum')),
                ('is_approved', models.BooleanField(default=False, help_text='Onaylanmadan sayfada görünmez', verbose_name='Onaylandı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product')),
            ],
            options={
                'verbose_name': 'Ürün Değerlendirmesi',
                'verbose_name_plural': 'Ürün Değerlendirmeleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
