# Generated by Django 5.0.4 on 2025-12-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sitesettings_whatsapp_number_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags_sq',
            field=models.CharField(blank=True, help_text='Të ndara me presje', max_length=200, verbose_name='Etiketat (Shqip)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags_tr',
            field=models.CharField(blank=True, help_text='Virgülle ayırarak etiketler girin', max_length=200, verbose_name='Etiketler (Türkçe)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Одделени со запирка', max_length=200, verbose_name='Етикети (Македонски)'),
        ),
    ]
