# Generated by Django 5.0.4 on 2025-12-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_blogpost_tags_sq_blogpost_tags_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Virgülle ayırarak etiketler girin', max_length=200, verbose_name='Етикети (Македонски)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags_sq',
            field=models.CharField(blank=True, help_text='Ndani me presje', max_length=200, verbose_name='Etiketat (Shqip)'),
        ),
    ]
