# Generated by Django 5.0.4 on 2025-12-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_pricingpackage_design_modifications_add_google_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemedia',
            name='section',
            field=models.CharField(choices=[('hero_home', 'Anasayfa - Hero 1 Arka Planı'), ('hero_home_2', 'Anasayfa - Hero 2 Arka Planı'), ('hero_home_stack_1', 'Anasayfa - Hero 2 Stack Resim 1'), ('hero_home_stack_2', 'Anasayfa - Hero 2 Stack Resim 2'), ('hero_home_floral', 'Anasayfa - Hero 2 Çiçek Dekorasyon'), ('dress_gallery_mini_1', 'Anasayfa - Dress Gallery Mini Resim 1'), ('dress_gallery_mini_2', 'Anasayfa - Dress Gallery Mini Resim 2'), ('dress_gallery_mini_3', 'Anasayfa - Dress Gallery Mini Resim 3'), ('bride_gallery_1', 'Anasayfa - Gelin Galerisi Resim 1'), ('bride_gallery_2', 'Anasayfa - Gelin Galerisi Resim 2'), ('bride_gallery_3', 'Anasayfa - Gelin Galerisi Resim 3'), ('bride_gallery_4', 'Anasayfa - Gelin Galerisi Resim 4'), ('bride_gallery_5', 'Anasayfa - Gelin Galerisi Resim 5'), ('about_hero', 'Hakkımızda - Hero Arka Planı'), ('services_banner', 'Hizmetler - Banner Arka Planı'), ('services_gallery', 'Hizmetler - Galeri Resimleri'), ('contact_gallery', 'İletişim - Galeri Resimleri'), ('faq_accommodation', 'SSS - Konaklama Resimleri'), ('portfolio_showcase', 'Portfolio - Galerideki Resimler'), ('rsvp_hero', 'RSVP - Hero Arka Planı')], max_length=50, verbose_name='Bölüm'),
        ),
    ]
