# Generated by Django 5.0.4 on 2025-12-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_pagemedia_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageMedia',
            fields=[
            ],
            options={
                'verbose_name': 'Hakkımızda Görseli',
                'verbose_name_plural': '📄 Hakkımızda - Görseller',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagemedia',),
        ),
        migrations.CreateModel(
            name='ContactsPageMedia',
            fields=[
            ],
            options={
                'verbose_name': 'İletişim Görseli',
                'verbose_name_plural': '📞 İletişim - Görseller',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagemedia',),
        ),
        migrations.CreateModel(
            name='FAQPageMedia',
            fields=[
            ],
            options={
                'verbose_name': 'SSS Görseli',
                'verbose_name_plural': '❓ SSS - Görseller',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagemedia',),
        ),
        migrations.CreateModel(
            name='HomeBrideGalleryMedia',
            fields=[
            ],
            options={
                'verbose_name': 'Gelin Galerisi Görseli',
                'verbose_name_plural': '🏠 Anasayfa - Gelin Galerisi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagemedia',),
        ),
        migrations.CreateModel(
            name='HomeDressGalleryMedia',
            fields=[
            ],
            options={
                'verbose_name': 'Dress Gallery Görseli',
                'verbose_name_plural': '🏠 Anasayfa - Dress Gallery',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagemedia',),
        ),
        migrations.CreateModel(
            name='HomeHeroMedia',
            fields=[
            ],
            options={
                'verbose_name': 'Anasayfa Hero Görseli',
                'verbose_name_plural': '🏠 Anasayfa - Hero Görselleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagemedia',),
        ),
        migrations.CreateModel(
            name='RSVPPageMedia',
            fields=[
            ],
            options={
                'verbose_name': 'RSVP Görseli',
                'verbose_name_plural': '📋 RSVP - Görseller',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagemedia',),
        ),
        migrations.CreateModel(
            name='ServicesPageMedia',
            fields=[
            ],
            options={
                'verbose_name': 'Hizmetler Görseli',
                'verbose_name_plural': '🛠️ Hizmetler - Görseller',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagemedia',),
        ),
    ]
