# Generated by Django 5.0.4 on 2025-12-26 02:26
# This migration only updates help_text for old tag fields (BlogTag already created in 0034)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_blogtag_blogpost_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Eski alan - artık kullanılmıyor', max_length=200, verbose_name='Етикети (Македонски)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags_sq',
            field=models.CharField(blank=True, help_text='Eski alan - artık kullanılmıyor', max_length=200, verbose_name='Etiketat (Shqip)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags_tr',
            field=models.CharField(blank=True, help_text='Eski alan - artık kullanılmıyor', max_length=200, verbose_name='Etiketler (Türkçe)'),
        ),
    ]
