# Generated by Django 6.0.1 on 2026-01-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_blogtag_alter_blogpost_tags_alter_blogpost_tags_sq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_header_branding',
            field=models.BooleanField(default=True, help_text="Header'da site adı ve slogan göster"),
        ),
    ]
