# Generated by Django 6.0.1 on 2026-01-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_sitesettings_show_header_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, default='Ankora Atelier', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='Bridal & Couture Studio', max_length=200),
        ),
    ]
