# Generated by Django 6.0.1 on 2026-01-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_sitesettings_site_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Önerilen boyut: 1200x675 piksel (16:9 yatay dikdörtgen)', null=True, upload_to='blog/'),
        ),
    ]
