# Generated by Django 6.0.1 on 2026-01-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_blogpost_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Önerilen boyut: 600x800 piksel (dikey dikdörtgen), maksimum 400KB', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Önerilen boyut: 800x450 piksel (16:9 yatay dikdörtgen), maksimum 400KB', null=True, upload_to='blog/'),
        ),
    ]
