# Generated by Django 6.0.1 on 2026-01-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_pagemedia_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_sq',
            field=models.CharField(blank=True, default='Me Marrëveshje', max_length=60, verbose_name='Çmimi (Shqip)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_tr',
            field=models.CharField(blank=True, default='Tafsiye Edilen Fiyat', max_length=60, verbose_name='Fiyat (Türkçe)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='По договор', max_length=60, verbose_name='Цена (Македонски)'),
        ),
    ]
